prd_paths:
  ArXiv_digest: "benchmark_data/python/ArXiv_digest/docs/PRD.md"
  chakin: "benchmark_data/python/chakin/PRD.md"
  geotext: "benchmark_data/python/geotext/PRD.md"
  hone: "benchmark_data/python/hone/docs/PRD.md"
  Hybrid_Images: "benchmark_data/python/Hybrid_Images/docs/PRD.md"
  lice: "benchmark_data/python/lice/PRD.md"
  particle-swarm-optimization: "benchmark_data/python/particle-swarm-optimization/docs/PRD.md"
  readtime: "benchmark_data/python/readtime/docs/PRD.md"
  stocktrends: "benchmark_data/python/stocktrends/docs/PRD.md"
  TextCNN: "benchmark_data/python/TextCNN/PRD.md"


